name: Release

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - name: Release please
              id: release
              uses: googleapis/release-please-action@v4
              with:
                  token: ${{ secrets.RELEASE_KEY }}
                  release-type: "node"
            - uses: actions/checkout@v3
              if: ${{steps.release.outputs.created_release}}
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
              if: ${{ steps.release.outputs.release_created }}
            - run: npm ci
              if: ${{ steps.release.outputs.release_created }}
            - run: npm publish
              if: ${{ steps.release.outputs.release_created }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
