name: Release

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  release-type: "node"
            - uses: actions/checkout@v4
              if: ${{steps.release.outputs.created_release}}
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
              if: ${{ steps.release.outputs.release_created }}
            - run: npm ci
              if: ${{ steps.release.outputs.release_created }}
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
              if: ${{ steps.release.outputs.release_created }}
